### ISSUE TITLE
Issues with Saving Functionality

### ISSUE THREAD

**Issue by mags612** [dhasterok/LaserMapExplorer#68]
**1. Saving Plots**
<img width="838" alt="Screenshot 2024-10-14 at 3 44 30 pm" src="https://github.com/user-attachments/assets/23c34a30-f26e-440f-b9c3-f3118194d5b4">
While data can be saved successfully, attempting to save a figure results in an error.

Traceback (most recent call last):
  File "/Users/maggie/Desktop/LaME/LaserMapExplorer/main.py", line 6174, in save_plot
    self.mpl_toolbar.save_figure()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/matplotlib/backends/backend_qt.py", line 829, in save_figure
    self.canvas.parent(), "Choose a filename to save to", start,
    ^^^^^^^^^^^^^^^^^^^^
TypeError: 'MainWindow' object is not callable

**2. Saving configuration**
<img width="603" alt="Screenshot 2024-10-14 at 4 03 47 pm" src="https://github.com/user-attachments/assets/9205955a-2b83-4cc1-b0e8-af7bcaf42fce">
Clicking the button to save profile/polygon/n-Dim configuration does not trigger any action.

**Comment by dhasterok** [comment]
Added save functionality for n-dimensional lists.
