### ISSUE TITLE
Multiple Polygon Selection Display Failure

### ISSUE THREAD

**Issue by mags612** [dhasterok/LaserMapExplorer#78]
<img width="313" alt="Screenshot 2024-10-30 at 1 30 57 pm" src="https://github.com/user-attachments/assets/0f143da2-b413-4c22-8bcf-026e65ac3bee">
The polygon display fails when multiple polygons are selected simultaneously. Instead of showing multiple shadowed regions, follow error received: 

Traceback (most recent call last):
  File "/Users/maggie/Desktop/LaME/LaserMapExplorer/main.py", line 5685, in update_SV
    self.plot_map_mpl(sample_id, field_type, field)
  File "/Users/maggie/Desktop/LaME/LaserMapExplorer/main.py", line 6534, in plot_map_mpl
    self.plot_small_histogram(map_df,field)
  File "/Users/maggie/Desktop/LaME/LaserMapExplorer/main.py", line 6993, in plot_small_histogram
    bin_width = (np.nanmax(array) - np.nanmin(array)) / self.default_bins
                 ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/numpy/lib/_nanfunctions_impl.py", line 493, in nanmax
    res = np.fmax.reduce(a, axis=axis, out=out, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: zero-size array to reduction operation fmax which has no identity

**Comment by mags612** [comment]
Issue 2: Polygon Deletion Error

Traceback (most recent call last):
  File "/Users/maggie/Desktop/LaME/LaserMapExplorer/main.py", line 805, in <lambda>
    self.toolButtonPolyDelete.clicked.connect(lambda: self.table_fcn.delete_row(self.tableWidgetPolyPoints))
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maggie/Desktop/LaME/LaserMapExplorer/src/TableFunctions.py", line 133, in delete_row
    if p_id in self.parent.polygon.lines[self.parent.sample_id]:
               ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PolygonManager' object has no attribute 'lines'
