### ISSUE TITLE
Profiling error

### ISSUE THREAD

**Issue by mags612** [dhasterok/LaserMapExplorer#79]
Profiling function is not working with the following error:

Traceback (most recent call last):
  File "/Users/maggie/Desktop/LaME/LaserMapExplorer/main.py", line 3680, in <lambda>
    plotWindow.scene().sigMouseClicked.connect(lambda event,array=self.array, k=field, plot=plotWindow: self.plot_clicked(event,array, k, plotWindow))
                                                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maggie/Desktop/LaME/LaserMapExplorer/main.py", line 2572, in plot_clicked
    self.profiling.plot_profile_scatter(event, array, k,v, plot, x, y,x_i, y_i)
  File "/Users/maggie/Desktop/LaME/LaserMapExplorer/src/Profile.py", line 397, in plot_profile_scatter
    self.plot_profiles()
  File "/Users/maggie/Desktop/LaME/LaserMapExplorer/src/Profile.py", line 607, in plot_profiles
    cmap = self.main_window.get_colormap()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MainWindow' object has no attribute 'get_colormap'

**Comment by mags612** [comment]
tried to match the new style structure with profile and it's working now
