### ISSUE TITLE
Ternary Plot and Heatmap

### ISSUE THREAD

**Issue by mags612** [dhasterok/LaserMapExplorer#86]
1. Ternay plot shows up after double clicking the triangular icon, but also get the following error:
Traceback (most recent call last):
  File "/Users/maggie/Desktop/LaME/LaserMapExplorer/main.py", line 4964, in plot_ternarymap
    self.style.set_style_widgets('ternary map')
  File "/Users/maggie/Desktop/LaME/LaserMapExplorer/src/app/StyleToolbox.py", line 1639, in set_style_widgets
    parent.update_field_type_combobox(parent.comboBoxColorByField,addNone=True,plot_type=plot_type)
  File "/Users/maggie/Desktop/LaME/LaserMapExplorer/main.py", line 2868, in update_field_type_combobox
    field_list.insert(0, 'None')
    ^^^^^^^^^^
UnboundLocalError: cannot access local variable 'field_list' where it is not associated with a value

2. Heatmap plot does not work (either with two or three elements), no error message.

**Comment by dhasterok** [comment]
Fixed.
