### ISSUE TITLE
Ratios not working

### ISSUE THREAD

**Issue by dhasterok** [dhasterok/LaserMapExplorer#9]
Ratios are being properly added from the analyte selection tool.  Gives the following error:

/Users/dhasterok/Documents/LaserMapExplorer/main.py:2871: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.data[sample_id]['computed_data']['Ratio'][ratio_name] = ratio_array
Traceback (most recent call last):
  File "/Users/dhasterok/Documents/LaserMapExplorer/main.py", line 1422, in open_select_analyte_dialog
    self.update_tree(self.data[self.sample_id]['norm'], norm_update = True)
  File "/Users/dhasterok/Documents/LaserMapExplorer/main.py", line 9054, in update_tree
    item,check = self.find_leaf('Ratio (normalize)', branch = self.sample_id, leaf = ratio_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dhasterok/Documents/LaserMapExplorer/main.py", line 9197, in find_leaf
    for index in range(tree_items.rowCount()):
                       ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'rowCount'

**Comment by dhasterok** [comment]
Done.  Though only changes for current sample.
